version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./sql_app.db
      - MONGODB_URI=mongodb://mongo:27017
      - MONGODB_DB_NAME=ct200_qa
      - GROQ_API_KEY=${GROQ_API_KEY}
    volumes:
      - .:/app
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
