name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:6.0
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v4
    
        
    - name: Run Pytest
      env:
        DATABASE_URL: sqlite:///./test.db
        MONGODB_URI: mongodb://localhost:27017
        MONGODB_DB_NAME: ct200_qa_test
      run: |
        pytest tests/ -v
